// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodeStructure.Controllers;

#nullable disable

namespace NodeStructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240526062112_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("NodeStructure.Models.NodesInfo", b =>
                {
                    b.Property<int>("nodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nodeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("parentNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("startDate")
                        .HasColumnType("TEXT");

                    b.HasKey("nodeId");

                    b.ToTable("nodesInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
